---
- name: Block IP Address using UFW on Ubuntu
  hosts: checkpoint
  become: true
  gather_facts: yes

  vars:
    blocked_ip: 192.168.56.101

  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Ensure UFW is enabled and started
      service:
        name: ufw
        state: started
        enabled: yes

    - name: Ensure UFW allows SSH
      command: ufw allow ssh
      register: ssh_allow_result
      changed_when: "'Skipping adding existing rule' not in ssh_allow_result.stdout"
      ignore_errors: true

    - name: Check if IP is already blocked
      become: true
      shell: ufw status verbose | grep "{{ blocked_ip }}"
      register: ufw_block_check
      ignore_errors: true
      changed_when: false

    - name: Add deny rule for blocked IP if not already present
      command: ufw deny from {{ blocked_ip }}
      when: ufw_block_check.rc != 0
      notify: Reload UFW

  handlers:
    - name: Reload UFW
      command: ufw reload
