- name: Block IP Address
  hosts: checkpoint
  become: true
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Ensure UFW is enabled and started
      service:
        name: ufw
        state: started
        enabled: yes

    - name: Check if rule already exists
      shell: ufw status | grep -q "192.168.56.101"
      register: ufw_check
      ignore_errors: true

    - name: Create new firewall rule if not exists
      ufw:
        rule: deny
        from: 192.168.56.108
      when: ufw_check.rc != 0

    - name: Restart UFW Firewall
      service:
        name: ufw
        state: restarted
        enabled: yes
