---
- name: Block IP address using acl_manager
  hosts: checkpoint
  connection: httpapi
  gather_facts: false

  vars:
    source_ip: 172.17.13.98
    destination_ip: 192.168.0.10
    ansible_network_os: checkpoint

  tasks:
    - name: Block the source IP
      include_role:
        name: acl_manager
        tasks_from: block_ip
