---
- name: Unified Playbook for Blocking and Unblocking IPs
  hosts: checkpoint
  connection: httpapi
  gather_facts: false

  vars:
    action: "block"  # Set to "block" or "unblock"
    source_ip: 172.17.13.98
    destination_ip: 192.168.0.10
    ansible_network_os: checkpoint

  tasks:
    - name: Block IP address
      include_role:
        name: acl_manager
        tasks_from: block_ip
      when: action == "block"
      tags: [block]

    - name: Unblock IP address
      include_role:
        name: acl_manager
        tasks_from: unblock_ip
      when: action == "unblock"
      tags: [unblock]
