---
- name: Block IP Address using UFW on Ubuntu
  hosts: checkpoint
  become: true
  gather_facts: yes

  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Ensure UFW is enabled and started
      service:
        name: ufw
        state: started
        enabled: yes

    - name: Ensure UFW allows SSH
      command: ufw allow ssh
      register: ssh_allow_result
      changed_when: "'Skipping adding existing rule' not in ssh_allow_result.stdout"
      ignore_errors: true

    - name: Check current UFW rules
      command: ufw status verbose
      register: ufw_status
      changed_when: false

    - name: Add deny rule for 192.168.56.102 if not already blocked
      command: ufw deny from 192.168.56.102
      when: "'192.168.56.102' not in ufw_status.stdout"
      notify:
        - Reload UFW

    - name: Reload UFW to apply any changes
      command: ufw reload
      when: "'192.168.56.102' not in ufw_status.stdout"

  handlers:
    - name: Reload UFW
      command: ufw reload
